### ISSUE TITLE
Please read CPU usage from cgroups

### ISSUE THREAD

**Issue by baryluk** [povilasv/systemd_exporter#1]
```
# cd /sys/fs/cgroup/cpu,cpuacct/system.slice/system-postgresql.slice/ 
/sys/fs/cgroup/cpu,cpuacct/system.slice/system-postgresql.slice# grep . *
cgroup.clone_children:0
cgroup.procs:29339
cgroup.procs:29347
cgroup.procs:29348
cgroup.procs:29349
cgroup.procs:29350
cgroup.procs:29351
cgroup.procs:29352
cpu.cfs_period_us:100000
cpu.cfs_quota_us:-1
cpu.shares:1024
cpu.stat:nr_periods 0
cpu.stat:nr_throttled 0
cpu.stat:throttled_time 0
cpuacct.stat:user 20058234
cpuacct.stat:system 2366001
cpuacct.usage:226172497330452
cpuacct.usage_all:cpu user system
cpuacct.usage_all:0 18539780026012 0
cpuacct.usage_all:1 19112412884900 0
cpuacct.usage_all:2 19701916584221 0
cpuacct.usage_all:3 20317941600822 0
cpuacct.usage_all:4 20888995199117 0
cpuacct.usage_all:5 21594195818507 0
cpuacct.usage_all:6 18114668406785 0
cpuacct.usage_all:7 18762775674265 0
cpuacct.usage_all:8 18074239278957 0
cpuacct.usage_all:9 17520573138224 0
cpuacct.usage_all:10 17137139841423 0
cpuacct.usage_all:11 16407858877219 0
cpuacct.usage_percpu:18539780026012 19112412884900 19701916584221 20317941600822 20888995199117 21594195818507 18114668406785 18762775674265 18074239278957 17520573138224 17137139841423 16407858877219 
cpuacct.usage_percpu_sys:0 0 0 0 0 0 0 0 0 0 0 0 
cpuacct.usage_percpu_user:18539780026012 19112412884900 19701916584221 20317941600822 20888995199117 21594195818507 18114668406785 18762775674265 18074239278957 17520573138224 17137139841423 16407858877219 
cpuacct.usage_sys:0
cpuacct.usage_user:226172497330452
notify_on_release:0
tasks:29339
tasks:29347
tasks:29348
tasks:29349
tasks:29350
tasks:29351
tasks:29352
# 
```

The current approach used by systemd_exporter is not applicable to many services.

1) It only monitors one process.
2) It might report incorrect data on service restart (it is okish, as the taking a rate over this metric should detect a metric reset).
3) Even if all processes are taken and added, it will result in wrong results, because processes might be short lived, missed by procfs reads, or might not be suitable for simple addition.

Taking info from cgroups is a way to go!  :) Added bonus: It is more reliable, more precise and faster.

I believe main values of interest are:

```
cpuacct.stat:user 20058229
cpuacct.stat:system 2365985
cpuacct.usage:226172281435124
...
cpuacct.usage_sys:0
cpuacct.usage_user:226172281435124
```

I am not sure what is a difference between the two tho.

**Comment by povilasv** [comment]
Cool, will definitely take a look. PRs are welcome.

**Comment by hamiltont** [comment]
Initial approach in #5

**Comment by hamiltont** [comment]
fixed in #5 :)

**Comment by baryluk** [comment]
Excellent. And thank you.

Also I see some comments to using `cpu` label in committed files. I think it is a very bad idea, and provides no useful information to justify the costs of storing it, so I don't even see reasons to include it in considerations or comments. Just FYI.

**Comment by hamiltont** [comment]
@baryluk thanks for the feedback. I'm not quite following you though - could you link to an example line?

**Comment by baryluk** [comment]
https://github.com/povilasv/systemd_exporter/blob/master/systemd/systemd.go#L128

It says
```go
// We could add a cpu label, but IMO that could cause a cardinality explosion. 
```

My point is, you SHOULD NOT add cpu label. And you are right it would cause cardinality explosion for essentially zero gain.

I commented on the PR on some other issue related to per-cpu data.

**Comment by hamiltont** [comment]
Ah, got it. I should rephrase that comment - I intended it as a warning specifically to *prevent* others from adding a CPU label in the future. Will try to tweak the phrasing in my other open PR

**Comment by baryluk** [comment]
@hamiltont Ok. Thanks again.

**Comment by rushi47** [comment]
@hamiltont am trying to calculate the cpu usage manually for some task and to cross validate, can you verify my approach once ?
