### ISSUE TITLE
Thoughts on filters?

### ISSUE THREAD

**Issue by till** [povilasv/systemd_exporter#11]
Hey!

Wondering what you think about a "filter" — could be a `--flag` or even a `GET` (or maybe `POST`) parameter to the endpoint. Reason/Context — I wanted to use this exporter to monitor a hypervisor. I am interested in specific units only, not everything.

Anyhow, I'd make a PR if you'd like. :)

**Comment by povilasv** [comment]
Hey,

Just like node-exporter we have two flags for that:

```
      --collector.unit-whitelist=".+"  
                             Regexp of systemd units to whitelist. Units must both match whitelist and not match blacklist to be
                             included.
      --collector.unit-blacklist=".+\\.(device)"  
                             Regexp of systemd units to blacklist. Units must both match whitelist and not match blacklist to be
                             included.
```

Does that work for you?

We should probably document this better in readme :)

**Comment by till** [comment]
Totally works. 🎉🎉🎉

**Comment by till** [comment]
There is no mention of it in the README, so something this:

```
--collector.unit-whitelist='^(cronyd|node-exp)\.unit$'
```

I'll send a PR later.

**Comment by povilasv** [comment]
Awesome thanks :)

**Comment by baryluk** [comment]
unit whitelist could be useful. In general metrics and units filters can be done on the prometheus side tho, which is more flexible, but this obviously will still make exporter produce more data than is needed and waste some resources.
