### ISSUE TITLE
Provide binaries with releases

### ISSUE THREAD

**Issue by paulfantom** [povilasv/systemd_exporter#13]
I wanted to add an ansible role for quickly installing this exporter on many hosts and it would be very helpful if this repository provided already-built binaries in release assets (like in node_exporter or prometheus).

**Comment by povilasv** [comment]
https://github.com/povilasv/systemd_exporter/releases/tag/v0.3.0-rc.2

Here you go :)

**Comment by relarson1** [comment]
> I wanted to add an ansible role for quickly installing this exporter on many hosts and it would be very helpful if this repository provided already-built binaries in release assets (like in node_exporter or prometheus).

@paulfantom   do you have an example of an ansible role for deploying systemd_exporter?

**Comment by paulfantom** [comment]
@relarson1 yes, but it is private right now. I'll do some cleanup tomorrow and ping you. Thanks for reminding me :)

**Comment by paulfantom** [comment]
Sorry it took so long, but here is an ansible role for installing systemd_exporter: https://github.com/cloudalchemy/ansible-systemd-exporter
